@startuml
title 콘서트 조회

actor User
participant "ConcertController" as CM
participant "ConcertService" as CS
participant "ConcertRepository" as CR

User -> CM: 콘서트 목록 조회 요청
CM -> CS: 콘서트 목록 조회
CS -> CR: 콘서트 목록 조회
CR --> CS: 콘서트 목록 반환
CS --> CM: 콘서트 목록 반환
CM --> User: 콘서트 목록 반환

User -> CM: 선택한 콘서트 회차 조회
CM -> CS: 콘서트 회차 조회
CS -> CR: 해당 콘서트 회차 조회
CR --> CS: 콘서트 회차 목록 반환
CS --> CM: 콘서트 회차 목록 반환
CM --> User: 회차 목록 반환
@enduml
